services:
  nginx:
    image: nginx
    volumes:
    - ./templates:/etc/nginx/templates
    - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
    networks:
      - web_serv
    depends_on:
      - auth_backend
      - post_backend
  
  mongodb:
    image: mongo:5.0
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    command: mongod --noauth
    volumes:
      - ./mongodb_data:/data/db
      - ./common/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - web_serv

  postgresql:
    image: postgres
    container_name: postgresql
    ports:
      - "5432:5432"
    volumes:
      - /postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=example
    networks:
      - web_serv
    restart: always

  post_backend:
    build: ./post_backend
    depends_on:
      - mongodb
    ports:
      - 4050:4050
    networks:
      - web_serv
    env_file:
      - ./post_backend/.env

  auth_backend:
    build: ./auth_backend
    depends_on:
      - postgresql
    ports:
      - 4051:4051
    networks:
      - web_serv
    env_file:
      - ./auth_backend/.env
  
volumes:
  mongodb_data:

networks:
  web_serv:
    driver: bridge